# Eventually want to use this for dependencies, but Android Studio is not ready

[versions]
androidx-core = "1.9.0-alpha03"
appcompat = "1.4.1"
constraintlayout = "2.1.3"
coroutines = "1.6.1"
expresso-core = "3.4.0"
ext-junit = "1.1.3"
hilt = "2.41"
junit = "4.13.2"
kotlin = "1.6.21"
legacy = "1.0.0"
lifecycle-extensions = "2.2.0"
lifecycle-viewmodel = "2.5.0-beta01"
lifecycle-compiler = "2.4.1"
logging-interceptor = "5.0.0-alpha.7"
material = "1.4.0"
material3 = "1.0.0-alpha10"
navigation-fragment = "2.4.2"
navigation-ui = "2.4.2"
preference = "1.2.0"
recyclerview = "1.2.1"
recyclerview-selection = "1.1.0"
retrofit = "2.9.0"
room = "2.4.1"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
expresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "expresso-core" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
legacy-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy" }
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel" }
lifecycle-compiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "lifecycle-compiler" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui" }
preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
recyclerview-selection = { group = "androidx.recyclerview", name = "recyclerview-selection", version.ref = "recyclerview-selection" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

[bundles]
hilt = ["hilt-android", "hilt-compose"]
lifecycle = ["lifecycle-extensions", "lifecycle-viewmodel"]
retrofit = ["retrofit", "moshi", "logging-interceptor"]
room = ["room-runtime", "room-compiler"]

[plugins]