# Eventually want to use this for dependencies, but Android Studio is not ready

[versions]
accompanist = "0.24.7-alpha"
androidx-core = "1.9.0-alpha03"
appcompat = "1.4.1"
compose = "1.2.0-alpha08"
compose-activity = "1.6.0-alpha03"
compose-navigation = "2.5.0-beta01"
coroutines = "1.6.1"
expresso-core = "3.4.0"
ext-junit = "1.1.3"
hilt = "2.41"
hilt-compose = "1.0.0"
junit = "4.13.2"
kotlin = "1.6.21"
legacy = "1.0.0"
lifecycle-extensions = "2.2.0"
lifecycle-viewmodel = "2.5.0-beta01"
lifecycle-compiler = "2.4.1"
logging-interceptor = "5.0.0-alpha.7"
material = "1.4.0"
material3 = "1.0.0-alpha10"
preference = "1.2.0"
retrofit = "2.9.0"
room = "2.4.1"

[libraries]
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-insets = { group = "com.google.accompanist", name = "accompanist-insets", version.ref = "accompanist" }
accompanist-uicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
expresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "expresso-core" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
legacy-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy" }
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel" }
lifecycle-compiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "lifecycle-compiler" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-compose = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
material3-compose = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material-icons-compose = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

[bundles]
accompanist = ["accompanist-swiperefresh", "accompanist-insets", "accompanist-uicontroller"]
compose = ["compose-activity", "compose-navigation", "material3-compose", "compose-runtime", "compose-ui", "compose-foundation", "material-compose", "material-icons-compose"]
hilt = ["hilt-android", "hilt-compose"]
lifecycle = ["lifecycle-extensions", "lifecycle-viewmodel"]
retrofit = ["retrofit", "moshi", "logging-interceptor"]
room = ["room-runtime", "room-compiler"]

[plugins]