# Eventually want to use this for dependencies, but Android Studio is not ready

[versions]
accompanist = "0.26.1-alpha"
agp = "7.2.2"
androidx-core = "1.8.0"
appcompat = "1.5.0"
activity = "1.6.0-rc01"
compose-compiler = "1.3.0"
compose-foundation = "1.3.0-beta01"
compose-material = "1.3.0-beta01"
compose-material3 = "1.0.0-beta01"
compose-runtime = "1.3.0-beta01"
compose-ui = "1.3.0-beta01"
coroutines = "1.6.4"
expresso-core = "3.4.0"
ext-junit = "1.1.3"
hilt = "2.43.2"
hilt-compose = "1.0.0"
junit = "4.13.2"
kotlin = "1.7.10"
kotlin-serialization = "1.3.3"
kotlin-serializaiton-converter = "0.8.0"
legacy = "1.0.0"
lifecycle-viewmodel = "2.6.0-alpha01"
logging-interceptor = "5.0.0-alpha.10"
material = "1.7.0-alpha02"
navigation = "2.5.1"
preference = "1.2.0"
retrofit = "2.9.0"
room = "2.4.3"

[libraries]
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-insets = { group = "com.google.accompanist", name = "accompanist-insets", version.ref = "accompanist" }
accompanist-uicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-foundation" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose-material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-material" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose-runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
expresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "expresso-core" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlin-serializaiton-converter" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
legacy-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging-interceptor" }
preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

[bundles]
accompanist = ["accompanist-swiperefresh", "accompanist-insets", "accompanist-uicontroller"]
compose = ["compose-activity", "compose-navigation", "compose-material3", "compose-runtime", "compose-ui", "compose-foundation", "compose-material", "compose-material-icons"]
hilt = ["hilt-android", "hilt-compose"]
kotlin-serialization = ["kotlin-serialization", "kotlin-serialization-converter"]
retrofit = ["retrofit", "logging-interceptor"]
room = ["room-runtime", "room-ktx"]

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }